services:
  django-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./django_service:/django_service
    environment:
      - DB_HOST=database
      - DB_NAME=django_service_db
      - DB_USER=admin
      - DB_PASS=1234

    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=django_service_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./django_service:/django_service
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=django_service_db
      - DB_USER=admin
      - DB_PASS=1234

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./django_service:/django_service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - '5555:5555'

