services:
  django-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./django_service:/django_service

    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"